LANGUAGES = {
    'Chinese': {
        'app_title': "账号管理系统 - v{version}",
        'new_version': " [有新版本]",
        'add_accounts': "添加账号",
        'import_txt': "导入TXT",
        'export_selected': "导出选中",
        'select_export_method': "选择导出方式",
        'txt_file': "TXT文件",
        'clipboard': "剪贴板",
        'refresh': "刷新",
        'search': "搜索:",
        'show_available_only': "只显示可用",
        'show_remarked_only': "只显示已备注",
        'show_passwords': '显示密码',
        'delete_selected': "删除选中",
        'select_all_toggle': "全选/取消全选",
        'batch_remark': "批量备注",
        'github_label': "GitHub: ImLTHQ/SteamAccountManager",
        'columns': {
            'index': "序号",
            'select': "选择",
            'account': "账号",
            'password': "密码",
            'status': "状态",
            'available_time': "可用时间",
            'remarks': "备注",
            'shortcut': "冷却时间",
            'others': "其它"
        },
        'status_available': "可用",
        'status_unavailable': "不可用",
        'remarks_options': ["清空", "一级", "二级"],
        'days': "天数:",
        'hours': "小时:",
        'confirm': "确定",
        'cancel': "取消",
        'input_error': "输入错误",
        'invalid_datetime': "无效的日期时间: {error}",
        'enter_accounts': "请输入账号和密码（每行一个，格式：账号----密码）:",
        'modify_available_time': "修改可用时间",
        'immediately_available': "立即可用",
        'custom_days_hours': "自定义天数/小时",
        'custom_remark': "自定义备注",
        'enter_custom_remark': "请输入自定义备注:",
        'import_success': "导入成功",
        'imported_new_accounts': "成功导入 {count} 个新账号",
        'import_no_new': "没有新的账号被导入（可能已存在或格式不正确）",
        'import_error': "导入错误",
        'import_failed': "导入文件失败: {error}",
        'add_success': "添加成功",
        'added_new_accounts': "成功添加 {count} 个新账号",
        'add_no_new': "没有新的账号被添加（可能已存在）",
        'save_failed': "保存失败",
        'save_error': "保存数据失败: {error}",
        'load_error': "加载错误",
        'load_failed': "加载数据失败: {error}",
        'delete_no_selected': "删除选中",
        'delete_no_accounts': "没有选中的账号可删除",
        'confirm_delete': "确认删除",
        'confirm_delete_msg': "确定要删除选中的 {count} 个账号吗?",
        'delete_success': "删除成功",
        'deleted_accounts': "{count} 个账号已删除",
        'export_no_selected': "导出选中",
        'export_no_accounts': "没有选中的账号可导出",
        'export_success': "导出成功",
        'exported_accounts': "成功导出 {count} 个账号到 {path}",
        'export_error': "导出错误",
        'export_failed': "导出文件失败: {error}",
        'batch_remark_success': "批量备注",
        'batch_remark_msg': "已为 {count} 个账号设置备注为: {remark}",
        'day': "天",
        'hour': "小时",
        'days': "天",
        'hours': "小时",
        'less_than_one_hour': "不足1小时",

        'shortcut_20h': "20小时",
        'shortcut_3d': "3天",
        'shortcut_7d': "7天",
        'shortcut_14d': "14天",
        'shortcut_31d': "31天",
        'shortcut_45d': "45天",
        'shortcut_181d': "181天",

        '_year': "年",
        '_month': "月",
        '_day': "日",
        '_hour': "时",
        '_minute': "分",

        'login_account': '登录此账号',
    },
    'English': {
        'app_title': "Steam Account Manager - v{version}",
        'new_version': " [New Version Available]",
        'add_accounts': "Add Accounts",
        'import_txt': "Import TXT",
        'export_selected': "Export Selected",
        'select_export_method': "Select Export Method",
        'txt_file': "TXT File",
        'clipboard': "Clipboard",
        'refresh': "Refresh",
        'search': "Search:",
        'show_available_only': "Show Available Only",
        'show_remarked_only': "Show Remarked Only",
        'show_passwords': 'Show Passwords',
        'delete_selected': "Delete Selected",
        'select_all_toggle': "Select All/None",
        'batch_remark': "Batch Remark",
        'github_label': "GitHub: ImLTHQ/SteamAccountManager",
        'columns': {
            'index': "No.",
            'select': "Select",
            'account': "Account",
            'password': "Password",
            'status': "Status",
            'available_time': "Available Time",
            'remarks': "Remarks",
            'shortcut': "Cooldown",
            'others': "Others"
        },
        'status_available': "Available",
        'status_unavailable': "Unavailable",
        'remarks_options': ["Clear", "Level 1", "Level 2"],
        'days': "Days:",
        'hours': "Hours:",
        'confirm': "OK",
        'cancel': "Cancel",
        'input_error': "Input Error",
        'invalid_datetime': "Invalid date/time: {error}",
        'enter_accounts': "Please enter accounts and passwords (one per line, format: account----password):",
        'modify_available_time': "Modify Available Time",
        'immediately_available': "Immediately Available",
        'custom_days_hours': "Custom Days/Hours",
        'custom_remark': "Custom Remark",
        'enter_custom_remark': "Please enter custom remark:",
        'import_success': "Import Successful",
        'imported_new_accounts': "Successfully imported {count} new accounts",
        'import_no_new': "No new accounts imported (may already exist or incorrect format)",
        'import_error': "Import Error",
        'import_failed': "Failed to import file: {error}",
        'add_success': "Add Successful",
        'added_new_accounts': "Successfully added {count} new accounts",
        'add_no_new': "No new accounts added (may already exist)",
        'save_failed': "Save Failed",
        'save_error': "Failed to save data: {error}",
        'load_error': "Load Error",
        'load_failed': "Failed to load data: {error}",
        'delete_no_selected': "Delete Selected",
        'delete_no_accounts': "No selected accounts to delete",
        'confirm_delete': "Confirm Delete",
        'confirm_delete_msg': "Are you sure you want to delete {count} selected accounts?",
        'delete_success': "Delete Successful",
        'deleted_accounts': "{count} accounts have been deleted",
        'export_no_selected': "Export Selected",
        'export_no_accounts': "No selected accounts to export",
        'export_success': "Export Successful",
        'exported_accounts': "Successfully exported {count} accounts to {path}",
        'export_error': "Export Error",
        'export_failed': "Failed to export file: {error}",
        'batch_remark_success': "Batch Remark",
        'batch_remark_msg': "Set remark for {count} accounts to: {remark}",
        'day': "day",
        'hour': "hour",
        'days': "days",
        'hours': "hours",
        'less_than_one_hour': "Less than 1 hour",

        'shortcut_20h': "20 hours",
        'shortcut_3d': "3 days",
        'shortcut_7d': "7 days",
        'shortcut_14d': "14 days",
        'shortcut_31d': "31 days",
        'shortcut_45d': "45 days",
        'shortcut_181d': "181 days",

        '_year': "Year",
        '_month': "Month",
        '_day': "Day",
        '_hour': "Hour",
        '_minute': "Minute",

        'login_account': 'Login this account',
    }
}