LANGUAGES = {
    'Chinese': {
        'app_title': "账号管理系统 - v{version}",
        'new_version': " [有新版本]",
        'add_accounts': "添加账号",
        'import_txt': "导入TXT",
        'export_selected': "导出选中",
        'select_export_method': "选择导出方式",
        'txt_file': "TXT文件",
        'clipboard': "剪贴板",
        'refresh': "刷新",
        'search': "搜索:",
        'show_available_only': "只显示可用",
        'show_remarked_only': "只显示已备注",
        'show_hidden': '显示隐藏',
        'delete_selected': "删除选中",
        'select_all_toggle': "全选/取消全选",
        'batch_remark': "批量备注",
        'github_label': "GitHub: ImLTHQ/SteamAccountManager",
        'columns': {
            'index': "序号",
            'select': "选择",
            'account': "账号",
            'password': "密码",
            'status': "状态",
            'available_time': "冷却结束时间",
            'remarks': "备注",
            'shortcut': "冷却时间",
            'others': "其它"
        },
        'status_available': "可用",
        'status_unavailable': "不可用",
        'remarks_options': ["清空", "一级", "二级"],
        'confirm': "确定",
        'cancel': "取消",
        'enter_accounts': "请输入账号和密码（每行一个，格式：账号----密码----其它）:",
        'custom_remark': "自定义备注",
        'enter_custom_remark': "请输入自定义备注:",
        'import_success': "导入成功",
        'imported_new_accounts': "成功导入 {count} 个新账号",
        'import_no_new': "没有新的账号被导入（可能已存在或格式不正确）",
        'import_error': "导入错误",
        'import_failed': "导入文件失败: {error}",
        'add_success': "添加成功",
        'added_new_accounts': "成功添加 {count} 个新账号",
        'add_no_new': "没有新的账号被添加（可能已存在）",
        'save_failed': "保存失败",
        'save_error': "保存数据失败: {error}",
        'load_error': "加载错误",
        'load_failed': "加载数据失败: {error}",
        'delete_no_selected': "删除选中",
        'delete_no_accounts': "没有选中的账号可删除",
        'confirm_delete': "确认删除",
        'confirm_delete_msg': "确定要删除选中的 {count} 个账号吗?",
        'delete_success': "删除成功",
        'deleted_accounts': "{count} 个账号已删除",
        'export_no_selected': "导出选中",
        'export_no_accounts': "没有选中的账号可导出",
        'export_success': "导出成功",
        'exported_accounts': "成功导出 {count} 个账号到 {path}",
        'export_error': "导出错误",
        'export_failed': "导出文件失败: {error}",
        'batch_remark_success': "批量备注",
        'batch_remark_msg': "已为 {count} 个账号设置备注为: {remark}",
        'day': "天",
        'hour': "小时",
        'days': "天",
        'hours': "小时",
        'less_than_one_hour': "不足1小时",

        'login_account': '登录此账号',

        'check_cooldown_selected': "查询VAC",
        'check_cooldown_no_selected': "查询VAC",
        'check_cooldown_no_accounts': "请选择账号重试",
        'check_cooldown_progress': "查询中",
        'check_cooldown_result': "查询结果",
        'check_cooldown_vac': "VAC封禁",
        'check_cooldown_no_ban': "无封禁",
        'check_cooldown_cooldown': "冷却中",
        'check_cooldown_fail': "查询失败",
        'check_cooldown_fail_title': "查询失败",
        'check_cooldown_fail_msg': "请尝试VPN/TUN代理/路由模式游戏加速器",
        'check_cooldown_retry_fail': "重试{count}次仍失败(请尝试VPN/TUN代理/路由模式游戏加速器)",
    },
    'English': {
        'app_title': "Steam Account Manager - v{version}",
        'new_version': " [New Version Available]",
        'add_accounts': "Add Accounts",
        'import_txt': "Import TXT",
        'export_selected': "Export Selected",
        'select_export_method': "Select Export Method",
        'txt_file': "TXT File",
        'clipboard': "Clipboard",
        'refresh': "Refresh",
        'search': "Search:",
        'show_available_only': "Available Only",
        'show_remarked_only': "Remarked Only",
        'show_hidden': 'Show Hidden',
        'delete_selected': "Delete Selected",
        'select_all_toggle': "Select All/Deselect",
        'batch_remark': "Batch Remark",
        'github_label': "GitHub: ImLTHQ/SteamAccountManager",
        'columns': {
            'index': "No.",
            'select': "Select",
            'account': "Account",
            'password': "Password",
            'status': "Status",
            'available_time': "Cooldown End Time",
            'remarks': "Remark",
            'shortcut': "Cooldown",
            'others': "Others"
        },
        'status_available': "Available",
        'status_unavailable': "Unavailable",
        'remarks_options': ["Clear", "Level 1", "Level 2"],
        'confirm': "Confirm",
        'cancel': "Cancel",
        'enter_accounts': "Enter accounts and passwords (one per line, format: account----password----others):",
        'custom_remark': "Custom Remark",
        'enter_custom_remark': "Enter custom remark:",
        'import_success': "Import Success",
        'imported_new_accounts': "Successfully imported {count} new accounts",
        'import_no_new': "No new accounts imported (may already exist or format incorrect)",
        'import_error': "Import Error",
        'import_failed': "Import file failed: {error}",
        'add_success': "Add Success",
        'added_new_accounts': "Successfully added {count} new accounts",
        'add_no_new': "No new accounts added (may already exist)",
        'save_failed': "Save Failed",
        'save_error': "Save data failed: {error}",
        'load_error': "Load Error",
        'load_failed': "Load data failed: {error}",
        'delete_no_selected': "Delete Selected",
        'delete_no_accounts': "No accounts selected to delete",
        'confirm_delete': "Confirm Delete",
        'confirm_delete_msg': "Delete {count} selected accounts?",
        'delete_success': "Delete Success",
        'deleted_accounts': "{count} accounts deleted",
        'export_no_selected': "Export Selected",
        'export_no_accounts': "No accounts selected to export",
        'export_success': "Export Success",
        'exported_accounts': "Exported {count} accounts to {path}",
        'export_error': "Export Error",
        'export_failed': "Export file failed: {error}",
        'batch_remark_success': "Batch Remark",
        'batch_remark_msg': "Set remark for {count} accounts to: {remark}",
        'day': "day",
        'hour': "hour",
        'days': "days",
        'hours': "hours",
        'less_than_one_hour': "Less than 1 hour",

        'login_account': 'Login Account',

        'check_cooldown_selected': "Check VAC",
        'check_cooldown_no_selected': "Check VAC",
        'check_cooldown_no_accounts': "Select account and retry",
        'check_cooldown_progress': "Checking",
        'check_cooldown_result': "Result",
        'check_cooldown_vac': "VAC Ban",
        'check_cooldown_no_ban': "No Ban",
        'check_cooldown_cooldown': "Cooldown",
        'check_cooldown_fail': "Query Failed",
        'check_cooldown_fail_title': "Query Failed",
        'check_cooldown_fail_msg': "Try VPN/TUN proxy/router-mode game accelerator",
        'check_cooldown_retry_fail': "{count} retries failed (try VPN/TUN proxy/router-mode game accelerator)",
    }
}